theme = "mytheme"

[editor]
auto-pairs = false
line-number = "relative"
mouse = false
rulers = [ 80 ]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = true